---
openapi: 3.0.3
servers:
- url: /api
components:
  parameters:
    user:
      description: this is users documentation.
      in: path
      name: users
      required: true
      schema:
        type: string
    comment:
      description: this is the comments documentation.
      in: path
      name: comment
      required: true
      schema:
        type: string
    recipe:
      description: this is the recipes documentation.
      in: path
      name: recipe
      required: true
      schema:
        type: string    
  schemas:
    user:
      properties:
        username:
          description: User's username
          type: string
        password:
          description: User's password
          type: string  
    

      required:
      - username
      - password
      type: object  
    
    Comment:
      properties:
        comment_body :
          description: The comment's body
          type: string


      required:
      - comment_body 
      type: object 
    
    Recipe:
      properties:
        recipe_title:
          description: The recipe's title
          type: string
        recipe_body :
          description: The recipe's body
          type: string


      required:
      - recipe_body 
      type: object   
    


info:
  title: Recipe Keeper
  version: 0.0.1
  description: |
    This is an API for food recipes.
    PWP course project.
    University of Oulu.
  termsOfService: http://totally.not.placehold.er/
  contact:
    url: http://totally.not.placehold.er/
    email: nmeftahi21@student.oulu.fi
    name: |
      Niloofar Meftahi
      Marwa Zabara
      Maha Eldamnhory
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html  

paths:
  /users/:
    get:
      description: Get the list of Users
      responses:
        '200':
          description: List of Users info
          content:
            application/json:
              example:
                - username: testusername1
                  password: testpass1
                - username: testusername2
                  password: testpass2
        
    post:
      description: Create a new User
      requestBody:
        description: JSON document that contains basic data for a new User
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'

            example:
              username: testusername1
              password: testpass1

      responses:
        '201':
          description: The User was created successfully
          headers:
            Location:
              description: URI of the new User
              schema:
                type: string
        '400':
          description: The request body was not valid
        '409':
          description: A User with the same username already exists
        '415':
          description: Unsupported media type
  /user/<user>/:
    parameters:
    - $ref: '#/components/parameters/user'
    put:
      description: Replace Users's data with new values
      requestBody:
        description: JSON document that contains new basic data for the user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
            example:
              username: new-testusername1
              
      responses:
        '204':
          description: The user's attributes were updated successfully
        '400':
          description: The request body was not valid
        '404':
          description: The user was not found
        '409':
          description: A user with the same username already exists
        '415':
          description: Unsupported media type
    delete:
     description: Delete the selected user
     responses:
       '204':
         description: The user was successfully deleted
       '404':
         description: The user was not found
############################################################
  /user/<user>/<recipe>/comment/:
    parameters:
    - $ref: '#/components/parameters/comment'
    get:
      description: Get the list of Comments
      responses:
        '200':
          description: List of Comments info
          content:
            application/json:
              example:
                - comment_body : comment1

                - comment_body : comment2
            
        
    post:
      description: Create a new Comment
      requestBody:
        description: JSON document that contains basic data for a new comment
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'

            example:
              comment_body : comment1

      responses:
        '201':
          description: The comment was created successfully
          headers:
            Location:
              description: URI of the new Comment
              schema:
                type: string
        '400':
          description: The request body was not valid
        '415':
          description: Unsupported media type
#############################################
  /user/<recipe>/comment/:
    parameters:
    - $ref: '#/components/parameters/comment'
    put:
      description: Replace comment's data with new values
      requestBody:
        description: JSON document that contains new basic data for the commment
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
            example:
              title: new-food1
              
      responses:
        '204':
          description: The comment's attributes were updated successfully
        '400':
          description: The request body was not valid
        '404':
          description: The comment was not found #????????
        '415':
          description: Unsupported media type
    delete:
     description: Delete the selected comment
     responses:
       '204':
         description: The comment was successfully deleted
       '404':
         description: The comment was not found
#################################################################
  /<user>/recipes/:
    parameters:
    - $ref: '#/components/parameters/recipe'
    get:
      description: Get the list of Recipes
      responses:
        '200':
          description: List of Recipes info
          content:
            application/json:
              example:
                - title: food1
                  content: content1
                - title: food2
                  content: content2
        
    post:
      description: Create a new Recipe
      requestBody:
        description: JSON document that contains basic data for a new recipe
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'

            example:
              title: food1
              content: content1

      responses:
        '201':
          description: The recipe was created successfully
          headers:
            Location:
              description: URI of the new Recipe
              schema:
                type: string
        '400':
          description: The request body was not valid
        '409':
          description: A recipe with the same title already exists
        '415':
          description: Unsupported media type
#############################################
  /recipes/<recipe>/:
    parameters:
    - $ref: '#/components/parameters/recipe'
    put:
      description: Replace recipe's data with new values
      requestBody:
        description: JSON document that contains new basic data for the recipe
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
            example:
              title: new-food1
              
      responses:
        '204':
          description: The recipe's attributes were updated successfully
        '400':
          description: The request body was not valid
        '404':
          description: The recipe was not found
        '409':
          description: A recipe with the same title already exists
        '415':
          description: Unsupported media type
    delete:
     description: Delete the selected recipe
     responses:
       '204':
         description: The recipe was successfully deleted
       '404':
         description: The recipe was not found
