---
openapi: 3.0.3
servers:
- url: /api
components:
  parameters:
    users:
      description: this is users documentation.
      in: path
      name: users
      required: true
      schema:
        type: string
  schemas:
    Users:
      properties:
        username:
          description: User's username
          type: string
        password:
          description: User's password
          type: string  


      required:
      - username
      - password
      type: object  


info:
  title: Recipe Keeper
  version: 0.0.1
  description: |
    This is an API for food recipes.
    PWP course project.
    University of Oulu.
  termsOfService: http://totally.not.placehold.er/
  contact:
    url: http://totally.not.placehold.er/
    email: nmeftahi21@student.oulu.fi
    name: |
      Niloofar Meftahi
      Marwa Zabara
      Maha Eldamnhory
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html  

paths:
  /users/:
    get:
      description: Get the list of Users
      responses:
        '200':
          description: List of Users info
          content:
            application/json:
              example:
                - username: testusername1
                  password: testpass1
                - username: testusername2
                  password: testpass2
        
    post:
      description: Create a new User
      requestBody:
        description: JSON document that contains basic data for a new User
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'

            example:
              username: testusername1
              password: testpass1

      responses:
        '201':
          description: The User was created successfully
          headers:
            Location:
              description: URI of the new User
              schema:
                type: string
        '400':
          description: The request body was not valid
        '409':
          description: A User with the same username already exists
        '415':
          description: Unsupported media type
    put:
      description: Replace Users's data with new values
      requestBody:
        description: JSON document that contains new basic data for the user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
            example:
              username: new-testusername1
              
      responses:
        '204':
          description: The user's attributes were updated successfully
        '400':
          description: The request body was not valid
        '404':
          description: The user was not found
        '409':
          description: A user with the same username already exists
        '415':
          description: Unsupported media type
    delete:
     description: Delete the selected user
     responses:
       '204':
         description: The user was successfully deleted
       '404':
         description: The user was not found
############################################################

