---
openapi: 3.0.3
servers:
- url: /api
components:
  parameters:
    comment:
      description: this is the comments documentation.
      in: path
      name: comment
      required: true
      schema:
        type: string
  schemas:
    Comment:
      properties:
        comment_body :
          description: The comment's body
          type: string


      required:
      - comment_body 
      type: object  

info:
  title: Recipe Keeper
  version: 0.0.1
  description: |
    This is an API for food recipes.
    PWP course project.
    University of Oulu.
  termsOfService: http://totally.not.placehold.er/
  contact:
    url: http://totally.not.placehold.er/
    email: nmeftahi21@student.oulu.fi
    name: |
      Niloofar Meftahi
      Marwa Zabara
      Maha Eldamnhory
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html  

paths:
  /comment/:
    get:
      description: Get the list of Comments
      responses:
        '200':
          description: List of Comments info
          content:
            application/json:
              example:
                - comment_body : comment1

                - comment_body : comment2
            
        
    post:
      description: Create a new Comment
      requestBody:
        description: JSON document that contains basic data for a new comment
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'

            example:
              comment_body : comment1

      responses:
        '201':
          description: The comment was created successfully
          headers:
            Location:
              description: URI of the new Comment
              schema:
                type: string
        '400':
          description: The request body was not valid
        '415':
          description: Unsupported media type
#############################################
    put:
      description: Replace comment's data with new values
      requestBody:
        description: JSON document that contains new basic data for the commment
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
            example:
              title: new-food1
              
      responses:
        '204':
          description: The comment's attributes were updated successfully
        '400':
          description: The request body was not valid
        '404':
          description: The comment was not found #????????
        '415':
          description: Unsupported media type
    delete:
     description: Delete the selected comment
     responses:
       '204':
         description: The comment was successfully deleted
       '404':
         description: The comment was not found